services:
  - docker
dist: trusty
sudo: required

env:
  global:

script:
  - echo $TRAVIS_BRANCH
  - make
  - make show

after_success:
  if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  make push;
  fi

