services:
  - docker
dist: trusty
sudo: required

env:
 - TARGET=5.5.38
 - TARGET=5.2.4
# - TARGET=ci1
# - TARGET=ci2
# - TARGET=ci3
# - TARGET=ci4
# - TARGET=ci5
# - TARGET=ci6
# - TARGET=ci7
# - TARGET=ci8
# - TARGET=ci9
# - TARGET=ci10
# - TARGET=ci11
# - TARGET=ci12
# - TARGET=ci13
# - TARGET=ci14
# - TARGET=ci15
# - TARGET=ci16

script:
  - echo $TRAVIS_BRANCH $TARGET
  - IMGPREFIX="$TRAVIS_BRANCH" make $TARGET
  - make show
  - make test
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then make push;  fi
