services:
  - docker
dist: trusty
sudo: required

env:
 - TARGET=5.2.4
 - TARGET=5.2.5
 - TARGET=5.2.6
 - TARGET=5.2.8
 - TARGET=5.2.9
 - TARGET=5.2.10
 - TARGET=5.2.11
 - TARGET=5.2.12
 - TARGET=5.2.13
 - TARGET=5.2.14
 - TARGET=5.2.15
 - TARGET=5.2.16
 - TARGET=5.2.17
 - TARGET=5.3.0
 - TARGET=5.3.1
 - TARGET=5.3.2
 - TARGET=5.3.3
 - TARGET=5.3.4
 - TARGET=5.3.5
 - TARGET=5.3.6
 - TARGET=5.3.7
 - TARGET=5.3.8
 - TARGET=5.3.9
 - TARGET=5.3.10
 - TARGET=5.3.11
 - TARGET=5.3.12
 - TARGET=5.3.13
 - TARGET=5.3.14
 - TARGET=5.3.15
 - TARGET=5.3.16
 - TARGET=5.3.17
 - TARGET=5.3.18
 - TARGET=5.3.19
 - TARGET=5.3.20
 - TARGET=5.3.21
 - TARGET=5.3.22
 - TARGET=5.3.23
 - TARGET=5.3.24
 - TARGET=5.3.25
 - TARGET=5.3.26
 - TARGET=5.3.27
 - TARGET=5.3.28
 - TARGET=5.3.29
 - TARGET=5.4.0
 - TARGET=5.4.1
 - TARGET=5.4.2
 - TARGET=5.4.3
 - TARGET=5.4.4
 - TARGET=5.4.5
 - TARGET=5.4.6
 - TARGET=5.4.7
 - TARGET=5.4.8
 - TARGET=5.4.9
 - TARGET=5.4.10
 - TARGET=5.4.11
 - TARGET=5.4.12
 - TARGET=5.4.13
 - TARGET=5.4.14
 - TARGET=5.4.15
 - TARGET=5.4.16
 - TARGET=5.4.17
 - TARGET=5.4.18
 - TARGET=5.4.19
 - TARGET=5.4.20
 - TARGET=5.4.21
 - TARGET=5.4.22
 - TARGET=5.4.23
 - TARGET=5.4.24
 - TARGET=5.4.25
 - TARGET=5.4.26
 - TARGET=5.4.27
 - TARGET=5.4.28
 - TARGET=5.4.29
 - TARGET=5.4.30
 - TARGET=5.4.31
 - TARGET=5.4.32
 - TARGET=5.4.33
 - TARGET=5.4.34
 - TARGET=5.4.35
 - TARGET=5.4.36
 - TARGET=5.4.37
 - TARGET=5.4.38
 - TARGET=5.4.39
 - TARGET=5.4.40
 - TARGET=5.4.41
 - TARGET=5.4.42
 - TARGET=5.4.43
 - TARGET=5.4.44
 - TARGET=5.4.45
 - TARGET=5.5.0
 - TARGET=5.5.1
 - TARGET=5.5.2
 - TARGET=5.5.3
 - TARGET=5.5.4
 - TARGET=5.5.5
 - TARGET=5.5.6
 - TARGET=5.5.7
 - TARGET=5.5.8
 - TARGET=5.5.9
 - TARGET=5.5.10
 - TARGET=5.5.11
 - TARGET=5.5.12
 - TARGET=5.5.13
 - TARGET=5.5.14
 - TARGET=5.5.15
 - TARGET=5.5.16
 - TARGET=5.5.17
 - TARGET=5.5.18
 - TARGET=5.5.19
 - TARGET=5.5.20
 - TARGET=5.5.21
 - TARGET=5.5.22
 - TARGET=5.5.23
 - TARGET=5.5.24
 - TARGET=5.5.25
 - TARGET=5.5.26
 - TARGET=5.5.27
 - TARGET=5.5.28
 - TARGET=5.5.29
 - TARGET=5.5.30
 - TARGET=5.5.31
 - TARGET=5.5.32
 - TARGET=5.5.33
 - TARGET=5.5.34
 - TARGET=5.5.35
 - TARGET=5.5.36
 - TARGET=5.5.37
 - TARGET=5.5.38
 - TARGET=5.6.0
 - TARGET=5.6.1
 - TARGET=5.6.2
 - TARGET=5.6.3
 - TARGET=5.6.4
 - TARGET=5.6.5
 - TARGET=5.6.6
 - TARGET=5.6.7
 - TARGET=5.6.8
 - TARGET=5.6.9
 - TARGET=5.6.10
 - TARGET=5.6.11
 - TARGET=5.6.12
 - TARGET=5.6.13
 - TARGET=5.6.14
 - TARGET=5.6.15
 - TARGET=5.6.16
 - TARGET=5.6.17
 - TARGET=5.6.18
 - TARGET=5.6.19
 - TARGET=5.6.20
 - TARGET=5.6.21
 - TARGET=5.6.22
 - TARGET=5.6.23
 - TARGET=5.6.24
 - TARGET=5.6.25
 - TARGET=5.6.26
 - TARGET=5.6.27
 - TARGET=5.6.28
 - TARGET=5.6.29
 - TARGET=5.6.30

script:
  - echo $TRAVIS_BRANCH $TARGET
  - if [ "$TRAVIS_BRANCH" == "master" ]; then IMGPREFIX="" make $TARGET; else IMGPREFIX="branch-$TRAVIS_BRANCH" make $TARGET; fi
  - make show
  - make test
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make push
